[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 1000

[fuzz]
runs = 5000

[rpc_endpoints]
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon_mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
polygon_mumbai = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config